# Generated by Django 4.2.2 on 2023-06-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipmentId', models.AutoField(primary_key=True, serialize=False)),
                ('regNum', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('registered', models.BooleanField(blank=True, null=True)),
                ('hasService', models.BooleanField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
